### ISSUE TITLE
为啥会一直识错误呢，是Tesseract-OCR不管用了吗，而且识别很慢

### ISSUE THREAD

**Issue by Wangdepp666** [wenz1xv/kaijutuoersuo#1]
RT

**Comment by wenz1xv** [comment]
是的，Tesseract-OCR效果可能与电脑有关，而且速度很慢。
考虑到只有固定的模板，经过测试用cv2做模板匹配就可以实现。
稍后会替换主分支为非ocr版本

**Comment by Wangdepp666** [comment]
非常谢谢您的更新，但是不知道为啥cv2模板的也不管用，识别是快了但是还是和之前一样错误，
![22222](https://github.com/wenz1xv/kaijutuoersuo/assets/67988442/29faa90a-8eb3-48d3-af6e-d627e78f7855)

**Comment by wenz1xv** [comment]
你好，这个问题是方块识别错误导致。
我已经修复方块识别，但是采用了绝对像素位置，不确定其他分辨率能否work。
已在1080p的windows与mac上测试通过。

**Comment by Wangdepp666** [comment]
感谢，1080p windows识别方块已经可用了，但是现在又出现了执行最优策略之后，鼠标滑动未成功消除，并停顿，我尝试一下自己解决，很感谢您
![111](https://github.com/wenz1xv/kaijutuoersuo/assets/67988442/f0e0ebb5-1586-45a7-b5ea-aaef2f9a0b54)

**Comment by wenz1xv** [comment]
测试了几个平台，窗口高度都为844，宽度为450，数字方块是固定像素进行识别的；
正常运行中不同策略分数一般不会一致，所以可能还是图片识别有问题，我尝试修复一下。

**Comment by wenz1xv** [comment]
> 感谢，1080p windows识别方块已经可用了，但是现在又出现了执行最优策略之后，鼠标滑动未成功消除，并停顿，我尝试一下自己解决，很感谢您 ![111](https://private-user-images.githubusercontent.com/67988442/315967748-f0e0ebb5-1586-45a7-b5ea-aaef2f9a0b54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDM1MTEsIm5iZiI6MTcxMTEwMzIxMSwicGF0aCI6Ii82Nzk4ODQ0Mi8zMTU5Njc3NDgtZjBlMGViYjUtMTU4Ni00NWE3LWI1ZWEtYWFlZjJmOWEwYjU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDEwMjY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZWMzYTI4NGY0ZjVkNGE0NWMwYTg4NDY5YjMxNDdiYzRjYjgyN2ZjNTFkMTJhZmQzMjRhMTZlNmY3OTc0N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FdO1YpxeQSU_dZsYXYoVs-6s1eipsh5HNFQH7vI8OS4)

如果方便的话，可以上传一下截图的shot.png文件吗？

**Comment by Wangdepp666** [comment]
但是我看我这shot.png也是正常的，
![shot](https://github.com/wenz1xv/kaijutuoersuo/assets/67988442/0311f6ce-bc0c-44dd-ae63-f1578f4e79f2)
![result_1711109385](https://github.com/wenz1xv/kaijutuoersuo/assets/67988442/c79853ca-17ed-4189-ab4e-aa5ae95f863c)
![1](https://github.com/wenz1xv/kaijutuoersuo/assets/67988442/5f64ea56-a4a7-41e3-a700-e13d13a877f9)

**Comment by Wangdepp666** [comment]
您好，我看了一下shot.png也是正常的
![shot](https://github.com/wenz1xv/kaijutuoersuo/assets/67988442/f08f664b-596c-4cf2-9d3a-41e1db6640fa)
![result_1711109770](https://github.com/wenz1xv/kaijutuoersuo/assets/67988442/f6e024c3-6477-4bf1-8f54-c010a40a96c0)
![Uploading yunxing.png…]()

**Comment by Wangdepp666** [comment]
您好，我看了一下shot.png也是对的，
![yunxing](https://github.com/wenz1xv/kaijutuoersuo/assets/67988442/1803a8fd-f755-4aee-b3f2-c9ed61f4021a)
![shot](https://github.com/wenz1xv/kaijutuoersuo/assets/67988442/3df1c12b-9f5d-4faa-83d3-20c33c8657a0)
![result_1711109770](https://github.com/wenz1xv/kaijutuoersuo/assets/67988442/9830a826-3167-41eb-b5a9-d0587137a467)
然后使用较高的分数门槛重开的话，都是正常的，应该还是执行算法的时候我这里有点毛病

**Comment by wenz1xv** [comment]
这个错误是由于您设备上的小程序窗口上方白条比开发测试时长11个像素，导致图像识别错位；
我已更新对像素位置的矫正，请尝试一下是否有效。
可以通过运行程序生成的shot.png、shot_reszie.png确认图像是否正确，正确情况下，以图片左上角为原点，第一个数字方格左上角坐标(20, 137)，右下角坐标为(51, 169)；可以通过shot.txt文件与shot.png内容是否一致判断图像识别是否正确。
如果还有问题的话请附上您的shot.png文件，我将尝试修复。

**Comment by Wangdepp666** [comment]
您好，您更新后我发现直接报错了
![报错](https://github.com/wenz1xv/kaijutuoersuo/assets/67988442/48d2eb30-dd84-4ad8-90d5-43e21646bb68)
然后shot.png是这样的
![shot](https://github.com/wenz1xv/kaijutuoersuo/assets/67988442/3957f763-a32a-47d5-a582-dc9400db443b)
但是shot.txt好像是因为报错就没有更新。
然后我就看了一下main.py代码里，这个import Quartz是什么东东勒，报错了
![Quartz](https://github.com/wenz1xv/kaijutuoersuo/assets/67988442/b3ae70bf-9f84-4bc3-a716-b200374548d2)

**Comment by wenz1xv** [comment]
你好，感谢你的关注和持续反馈。
Quartz是mac用于识别的工具，在windows上不会被引用，不影响程序的运行。

您可以再尝试一下现在修复后的版本。

通过观察您的日志应该是左上角锚点识别错误，识别空方块的过程导致报错。
此外，如果您对比截图与给出的示例，可以发现您的截图比示例略大一些，这导致识别方块出现错位。
这些问题应该已经得到修复，希望您能顺利运行。

**Comment by Wangdepp666** [comment]
感谢您的帮助，现在可以实现功能了，我会研究学习一下实现原理，十分感谢
